(* Generated by ocaml-tree-sitter. *)
(*
   c grammar

   entrypoint: translation_unit
*)

open! Sexplib.Conv
open Tree_sitter_run

type imm_tok_lpar = Token.t (* "(" *)
[@@deriving sexp_of]

type false_ = Token.t
[@@deriving sexp_of]

type anon_choice_BANG_67174d6 = [
    `BANG of Token.t (* "!" *)
  | `TILDE of Token.t (* "~" *)
  | `DASH of Token.t (* "-" *)
  | `PLUS of Token.t (* "+" *)
]
[@@deriving sexp_of]

type imm_tok_pat_36637e2 = Token.t (* pattern "[^\\n']" *)
[@@deriving sexp_of]

type pat_c3ea183 = Token.t (* pattern #[ 	]*define *)
[@@deriving sexp_of]

type primitive_type = Token.t
[@@deriving sexp_of]

type type_qualifier = [
    `Const of Token.t (* "const" *)
  | `Vola of Token.t (* "volatile" *)
  | `Rest of Token.t (* "restrict" *)
  | `X__Atomic of Token.t (* "_Atomic" *)
]
[@@deriving sexp_of]

type imm_tok_prec_p1_pat_c7f65b4 = Token.t (* pattern "[^\\\\\"\\n]+" *)
[@@deriving sexp_of]

type identifier = Token.t (* pattern [a-zA-Z_]\w* *)
[@@deriving sexp_of]

type true_ = Token.t
[@@deriving sexp_of]

type pat_56631e5 = Token.t (* pattern #[ 	]*else *)
[@@deriving sexp_of]

type pat_3df6e71 = Token.t (* pattern #[ 	]*if *)
[@@deriving sexp_of]

type escape_sequence = Token.t
[@@deriving sexp_of]

type pat_c46d1b2 = Token.t (* pattern #[ 	]*endif *)
[@@deriving sexp_of]

type storage_class_specifier = [
    `Extern of Token.t (* "extern" *)
  | `Static of Token.t (* "static" *)
  | `Auto of Token.t (* "auto" *)
  | `Regi of Token.t (* "register" *)
  | `Inline of Token.t (* "inline" *)
]
[@@deriving sexp_of]

type ms_call_modifier = [
    `X___cdecl of Token.t (* "__cdecl" *)
  | `X___clrc of Token.t (* "__clrcall" *)
  | `X___stdc of Token.t (* "__stdcall" *)
  | `X___fast of Token.t (* "__fastcall" *)
  | `X___this of Token.t (* "__thiscall" *)
  | `X___vect of Token.t (* "__vectorcall" *)
]
[@@deriving sexp_of]

type pat_9d92f6a = Token.t (* pattern #[ 	]*ifndef *)
[@@deriving sexp_of]

type pat_ca8830e = Token.t (* pattern #[ 	]*include *)
[@@deriving sexp_of]

type ms_unaligned_ptr_modifier = [
    `X__unal of Token.t (* "_unaligned" *)
  | `X___unal of Token.t (* "__unaligned" *)
]
[@@deriving sexp_of]

type system_lib_string = Token.t
[@@deriving sexp_of]

type pat_bfeb4bb = Token.t (* pattern #[ 	]*elif *)
[@@deriving sexp_of]

type number_literal = Token.t
[@@deriving sexp_of]

type pat_25b90ba = Token.t (* pattern #[ 	]*ifdef *)
[@@deriving sexp_of]

type preproc_directive = Token.t (* pattern #[ \t]*[a-zA-Z]\w* *)
[@@deriving sexp_of]

type preproc_arg = Token.t
[@@deriving sexp_of]

type anon_choice_DASHDASH_d11def2 = [
    `DASHDASH of Token.t (* "--" *)
  | `PLUSPLUS of Token.t (* "++" *)
]
[@@deriving sexp_of]

type string_literal = (
    [
        `LDQUOT of Token.t (* "L\"" *)
      | `UDQUOT_c163aae of Token.t (* "u\"" *)
      | `UDQUOT_df3447d of Token.t (* "U\"" *)
      | `U8DQUOT of Token.t (* "u8\"" *)
      | `DQUOT of Token.t (* "\"" *)
    ]
  * [
        `Imm_tok_prec_p1_pat_c7f65b4 of imm_tok_prec_p1_pat_c7f65b4
      | `Esc_seq of escape_sequence (*tok*)
    ]
      list (* zero or more *)
  * Token.t (* "\"" *)
)
[@@deriving sexp_of]

type char_literal = (
    [
        `LSQUOT of Token.t (* "L'" *)
      | `USQUOT_d861d39 of Token.t (* "u'" *)
      | `USQUOT_2701bdc of Token.t (* "U'" *)
      | `U8SQUOT of Token.t (* "u8'" *)
      | `SQUOT of Token.t (* "'" *)
    ]
  * [
        `Esc_seq of escape_sequence (*tok*)
      | `Imm_tok_pat_36637e2 of imm_tok_pat_36637e2
    ]
  * Token.t (* "'" *)
)
[@@deriving sexp_of]

type anon_choice_pat_25b90ba_4a37f8c = [
    `Pat_25b90ba of pat_25b90ba
  | `Pat_9d92f6a of pat_9d92f6a
]
[@@deriving sexp_of]

type ms_pointer_modifier = [
    `Ms_unal_ptr_modi of ms_unaligned_ptr_modifier (*tok*)
  | `Ms_rest_modi of Token.t (* "__restrict" *)
  | `Ms_unsi_ptr_modi of Token.t (* "__uptr" *)
  | `Ms_signed_ptr_modi of Token.t (* "__sptr" *)
]
[@@deriving sexp_of]

type preproc_call = (
    preproc_directive (*tok*)
  * preproc_arg (*tok*) option
  * Token.t (* "\n" *)
)
[@@deriving sexp_of]

type field_designator = (Token.t (* "." *) * identifier (*tok*))
[@@deriving sexp_of]

type preproc_defined = [
    `Defi_LPAR_id_RPAR of (
        Token.t (* "defined" *) * Token.t (* "(" *) * identifier (*tok*)
      * Token.t (* ")" *)
    )
  | `Defi_id of (Token.t (* "defined" *) * identifier (*tok*))
]
[@@deriving sexp_of]

type anon_choice_type_id_d3c4b5f = [
    `Id of identifier (*tok*)
  | `DOTDOTDOT of Token.t (* "..." *)
]
[@@deriving sexp_of]

type ms_declspec_modifier = (
    Token.t (* "__declspec" *) * Token.t (* "(" *) * identifier (*tok*)
  * Token.t (* ")" *)
)
[@@deriving sexp_of]

type preproc_def = (
    pat_c3ea183
  * identifier (*tok*)
  * preproc_arg (*tok*) option
  * Token.t (* "\n" *)
)
[@@deriving sexp_of]

type preproc_argument_list = (
    Token.t (* "(" *)
  * (
        preproc_expression (*tok*)
      * (Token.t (* "," *) * preproc_expression (*tok*))
          list (* zero or more *)
    )
      option
  * Token.t (* ")" *)
)

and preproc_binary_expression = [
    `Prep_exp_PLUS_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "+" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_DASH_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "-" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_STAR_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "*" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_SLASH_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "/" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_PERC_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "%" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_BARBAR_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "||" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_AMPAMP_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "&&" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_BAR_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "|" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_HAT_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "^" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_AMP_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "&" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_EQEQ_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "==" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_BANGEQ_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "!=" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_GT_prep_exp of (
        preproc_expression (*tok*) * Token.t (* ">" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_GTEQ_prep_exp of (
        preproc_expression (*tok*) * Token.t (* ">=" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_LTEQ_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "<=" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_LT_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "<" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_LTLT_prep_exp of (
        preproc_expression (*tok*) * Token.t (* "<<" *)
      * preproc_expression (*tok*)
    )
  | `Prep_exp_GTGT_prep_exp of (
        preproc_expression (*tok*) * Token.t (* ">>" *)
      * preproc_expression (*tok*)
    )
]

and preproc_call_expression = (
    identifier (*tok*) * preproc_argument_list (*tok*)
)

and preproc_expression = [
    `Id of identifier (*tok*)
  | `Prep_call_exp of preproc_call_expression (*tok*)
  | `Num_lit of number_literal (*tok*)
  | `Char_lit of char_literal (*tok*)
  | `Prep_defi of preproc_defined (*tok*)
  | `Prep_un_exp of (
        anon_choice_BANG_67174d6 (*tok*) * preproc_expression (*tok*)
    )
  | `Prep_bin_exp of preproc_binary_expression (*tok*)
  | `Prep_paren_exp of (
        Token.t (* "(" *) * preproc_expression (*tok*) * Token.t (* ")" *)
    )
]
[@@deriving sexp_of]

type preproc_params = (
    imm_tok_lpar (*tok*)
  * (
        anon_choice_type_id_d3c4b5f (*tok*)
      * (Token.t (* "," *) * anon_choice_type_id_d3c4b5f (*tok*))
          list (* zero or more *)
    )
      option
  * Token.t (* ")" *)
)
[@@deriving sexp_of]

type preproc_function_def = (
    pat_c3ea183
  * identifier (*tok*)
  * preproc_params (*tok*)
  * preproc_arg (*tok*) option
  * Token.t (* "\n" *)
)
[@@deriving sexp_of]

type abstract_declarator = [
    `Abst_poin_decl of (
        Token.t (* "*" *)
      * type_qualifier (*tok*) list (* zero or more *)
      * abstract_declarator (*tok*) option
    )
  | `Abst_func_decl of (
        abstract_declarator (*tok*) option
      * parameter_list (*tok*)
    )
  | `Abst_array_decl of (
        abstract_declarator (*tok*) option
      * Token.t (* "[" *)
      * type_qualifier (*tok*) list (* zero or more *)
      * anon_choice_exp_508611b (*tok*) option
      * Token.t (* "]" *)
    )
  | `Abst_paren_decl of (
        Token.t (* "(" *) * abstract_declarator (*tok*) * Token.t (* ")" *)
    )
]

and anon_choice_exp_508611b = [
    `Exp of expression (*tok*)
  | `STAR of Token.t (* "*" *)
]

and anon_choice_exp_55b4dba = [
    `Exp of expression (*tok*)
  | `Comma_exp of (
        expression (*tok*) * Token.t (* "," *)
      * anon_choice_exp_55b4dba (*tok*)
    )
]

and anon_choice_init_pair_1a6981e = [
    `Init_pair of (
        [
            `Subs_desi of subscript_designator (*tok*)
          | `Field_desi of field_designator (*tok*)
        ]
          list (* one or more *)
      * Token.t (* "=" *)
      * [
            `Exp of expression (*tok*)
          | `Init_list of initializer_list (*tok*)
        ]
    )
  | `Exp of expression (*tok*)
  | `Init_list of initializer_list (*tok*)
]

and anon_choice_param_decl_bdc8cc9 = [
    `Param_decl of (
        declaration_specifiers (*tok*)
      * [
            `Decl of declarator (*tok*)
          | `Abst_decl of abstract_declarator (*tok*)
        ]
          option
    )
  | `DOTDOTDOT of Token.t (* "..." *)
]

and anon_choice_prep_else_in_field_decl_list_97ea65e = [
    `Prep_else_in_field_decl_list of (
        pat_56631e5
      * field_declaration_list_item (*tok*) list (* zero or more *)
    )
  | `Prep_elif_in_field_decl_list of (
        pat_bfeb4bb
      * preproc_expression (*tok*)
      * Token.t (* "\n" *)
      * field_declaration_list_item (*tok*) list (* zero or more *)
      * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
    )
]

and anon_choice_stor_class_spec_5764fed = [
    `Stor_class_spec of storage_class_specifier (*tok*)
  | `Type_qual of type_qualifier (*tok*)
  | `Attr_spec of attribute_specifier (*tok*)
  | `Ms_decl_modi of ms_declspec_modifier (*tok*)
]

and anon_choice_type_id_opt_field_decl_list_9aebd83 = [
    `Id_opt_field_decl_list of (
        identifier (*tok*)
      * field_declaration_list (*tok*) option
    )
  | `Field_decl_list of field_declaration_list (*tok*)
]

and argument_list = (
    Token.t (* "(" *)
  * (
        expression (*tok*)
      * (Token.t (* "," *) * expression (*tok*)) list (* zero or more *)
    )
      option
  * Token.t (* ")" *)
)

and assignment_left_expression = [
    `Id of identifier (*tok*)
  | `Call_exp of call_expression (*tok*)
  | `Field_exp of field_expression (*tok*)
  | `Poin_exp of pointer_expression (*tok*)
  | `Subs_exp of subscript_expression (*tok*)
  | `Paren_exp of parenthesized_expression (*tok*)
]

and attribute_specifier = (
    Token.t (* "__attribute__" *) * Token.t (* "(" *) * argument_list (*tok*)
  * Token.t (* ")" *)
)

and binary_expression = [
    `Exp_PLUS_exp of (
        expression (*tok*) * Token.t (* "+" *) * expression (*tok*)
    )
  | `Exp_DASH_exp of (
        expression (*tok*) * Token.t (* "-" *) * expression (*tok*)
    )
  | `Exp_STAR_exp of (
        expression (*tok*) * Token.t (* "*" *) * expression (*tok*)
    )
  | `Exp_SLASH_exp of (
        expression (*tok*) * Token.t (* "/" *) * expression (*tok*)
    )
  | `Exp_PERC_exp of (
        expression (*tok*) * Token.t (* "%" *) * expression (*tok*)
    )
  | `Exp_BARBAR_exp of (
        expression (*tok*) * Token.t (* "||" *) * expression (*tok*)
    )
  | `Exp_AMPAMP_exp of (
        expression (*tok*) * Token.t (* "&&" *) * expression (*tok*)
    )
  | `Exp_BAR_exp of (
        expression (*tok*) * Token.t (* "|" *) * expression (*tok*)
    )
  | `Exp_HAT_exp of (
        expression (*tok*) * Token.t (* "^" *) * expression (*tok*)
    )
  | `Exp_AMP_exp of (
        expression (*tok*) * Token.t (* "&" *) * expression (*tok*)
    )
  | `Exp_EQEQ_exp of (
        expression (*tok*) * Token.t (* "==" *) * expression (*tok*)
    )
  | `Exp_BANGEQ_exp of (
        expression (*tok*) * Token.t (* "!=" *) * expression (*tok*)
    )
  | `Exp_GT_exp of (
        expression (*tok*) * Token.t (* ">" *) * expression (*tok*)
    )
  | `Exp_GTEQ_exp of (
        expression (*tok*) * Token.t (* ">=" *) * expression (*tok*)
    )
  | `Exp_LTEQ_exp of (
        expression (*tok*) * Token.t (* "<=" *) * expression (*tok*)
    )
  | `Exp_LT_exp of (
        expression (*tok*) * Token.t (* "<" *) * expression (*tok*)
    )
  | `Exp_LTLT_exp of (
        expression (*tok*) * Token.t (* "<<" *) * expression (*tok*)
    )
  | `Exp_GTGT_exp of (
        expression (*tok*) * Token.t (* ">>" *) * expression (*tok*)
    )
]

and bitfield_clause = (Token.t (* ":" *) * expression (*tok*))

and call_expression = (expression (*tok*) * argument_list (*tok*))

and declaration_specifiers = (
    anon_choice_stor_class_spec_5764fed (*tok*) list (* zero or more *)
  * type_specifier (*tok*)
  * anon_choice_stor_class_spec_5764fed (*tok*) list (* zero or more *)
)

and declarator = [
    `Poin_decl of (
        ms_based_modifier (*tok*) option
      * Token.t (* "*" *)
      * ms_pointer_modifier (*tok*) list (* zero or more *)
      * type_qualifier (*tok*) list (* zero or more *)
      * declarator (*tok*)
    )
  | `Func_decl of (
        declarator (*tok*)
      * parameter_list (*tok*)
      * attribute_specifier (*tok*) list (* zero or more *)
    )
  | `Array_decl of (
        declarator (*tok*)
      * Token.t (* "[" *)
      * type_qualifier (*tok*) list (* zero or more *)
      * anon_choice_exp_508611b (*tok*) option
      * Token.t (* "]" *)
    )
  | `Paren_decl of (
        Token.t (* "(" *) * declarator (*tok*) * Token.t (* ")" *)
    )
  | `Id of identifier (*tok*)
]

and enumerator = (
    identifier (*tok*)
  * (Token.t (* "=" *) * expression (*tok*)) option
)

and enumerator_list = (
    Token.t (* "{" *)
  * (
        enumerator (*tok*)
      * (Token.t (* "," *) * enumerator (*tok*)) list (* zero or more *)
    )
      option
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and expression = [
    `Cond_exp of (
        expression (*tok*) * Token.t (* "?" *) * expression (*tok*)
      * Token.t (* ":" *) * expression (*tok*)
    )
  | `Assign_exp of (
        assignment_left_expression (*tok*)
      * [
            `EQ of Token.t (* "=" *)
          | `STAREQ of Token.t (* "*=" *)
          | `SLASHEQ of Token.t (* "/=" *)
          | `PERCEQ of Token.t (* "%=" *)
          | `PLUSEQ of Token.t (* "+=" *)
          | `DASHEQ of Token.t (* "-=" *)
          | `LTLTEQ of Token.t (* "<<=" *)
          | `GTGTEQ of Token.t (* ">>=" *)
          | `AMPEQ of Token.t (* "&=" *)
          | `HATEQ of Token.t (* "^=" *)
          | `BAREQ of Token.t (* "|=" *)
        ]
      * expression (*tok*)
    )
  | `Bin_exp of binary_expression (*tok*)
  | `Un_exp of (anon_choice_BANG_67174d6 (*tok*) * expression (*tok*))
  | `Update_exp of update_expression (*tok*)
  | `Cast_exp of (
        Token.t (* "(" *) * type_descriptor (*tok*) * Token.t (* ")" *)
      * expression (*tok*)
    )
  | `Poin_exp of pointer_expression (*tok*)
  | `Sizeof_exp of (
        Token.t (* "sizeof" *)
      * [
            `Exp of expression (*tok*)
          | `LPAR_type_desc_RPAR of (
                Token.t (* "(" *) * type_descriptor (*tok*)
              * Token.t (* ")" *)
            )
        ]
    )
  | `Subs_exp of subscript_expression (*tok*)
  | `Call_exp of call_expression (*tok*)
  | `Field_exp of field_expression (*tok*)
  | `Comp_lit_exp of (
        Token.t (* "(" *) * type_descriptor (*tok*) * Token.t (* ")" *)
      * initializer_list (*tok*)
    )
  | `Id of identifier (*tok*)
  | `Num_lit of number_literal (*tok*)
  | `Str_lit of string_literal (*tok*)
  | `True of true_ (*tok*)
  | `False of false_ (*tok*)
  | `Null of Token.t (* "NULL" *)
  | `Conc_str of (
        string_literal (*tok*)
      * string_literal (*tok*) list (* one or more *)
    )
  | `Char_lit of char_literal (*tok*)
  | `Paren_exp of parenthesized_expression (*tok*)
]

and field_declaration_list = (
    Token.t (* "{" *)
  * field_declaration_list_item (*tok*) list (* zero or more *)
  * Token.t (* "}" *)
)

and field_declaration_list_item = [
    `Field_decl of (
        declaration_specifiers (*tok*)
      * (
            field_declarator (*tok*)
          * (Token.t (* "," *) * field_declarator (*tok*))
              list (* zero or more *)
        )
          option
      * bitfield_clause (*tok*) option
      * Token.t (* ";" *)
    )
  | `Prep_def of preproc_def (*tok*)
  | `Prep_func_def of preproc_function_def (*tok*)
  | `Prep_call of preproc_call (*tok*)
  | `Prep_if_in_field_decl_list of (
        pat_3df6e71
      * preproc_expression (*tok*)
      * Token.t (* "\n" *)
      * field_declaration_list_item (*tok*) list (* zero or more *)
      * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
      * pat_c46d1b2
    )
  | `Prep_ifdef_in_field_decl_list of (
        anon_choice_pat_25b90ba_4a37f8c (*tok*)
      * identifier (*tok*)
      * field_declaration_list_item (*tok*) list (* zero or more *)
      * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
      * pat_c46d1b2
    )
]

and field_declarator = [
    `Poin_field_decl of (
        ms_based_modifier (*tok*) option
      * Token.t (* "*" *)
      * ms_pointer_modifier (*tok*) list (* zero or more *)
      * type_qualifier (*tok*) list (* zero or more *)
      * field_declarator (*tok*)
    )
  | `Func_field_decl of (field_declarator (*tok*) * parameter_list (*tok*))
  | `Array_field_decl of (
        field_declarator (*tok*)
      * Token.t (* "[" *)
      * type_qualifier (*tok*) list (* zero or more *)
      * anon_choice_exp_508611b (*tok*) option
      * Token.t (* "]" *)
    )
  | `Paren_field_decl of (
        Token.t (* "(" *) * field_declarator (*tok*) * Token.t (* ")" *)
    )
  | `Id of identifier (*tok*)
]

and field_expression = (
    expression (*tok*)
  * [ `DOT of Token.t (* "." *) | `DASHGT of Token.t (* "->" *) ]
  * identifier (*tok*)
)

and initializer_list = (
    Token.t (* "{" *)
  * (
        anon_choice_init_pair_1a6981e (*tok*)
      * (Token.t (* "," *) * anon_choice_init_pair_1a6981e (*tok*))
          list (* zero or more *)
    )
      option
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and ms_based_modifier = (Token.t (* "__based" *) * argument_list (*tok*))

and parameter_list = (
    Token.t (* "(" *)
  * (
        anon_choice_param_decl_bdc8cc9 (*tok*)
      * (Token.t (* "," *) * anon_choice_param_decl_bdc8cc9 (*tok*))
          list (* zero or more *)
    )
      option
  * Token.t (* ")" *)
)

and parenthesized_expression = (
    Token.t (* "(" *) * anon_choice_exp_55b4dba (*tok*) * Token.t (* ")" *)
)

and pointer_expression = (
    [ `STAR of Token.t (* "*" *) | `AMP of Token.t (* "&" *) ]
  * expression (*tok*)
)

and subscript_designator = (
    Token.t (* "[" *) * expression (*tok*) * Token.t (* "]" *)
)

and subscript_expression = (
    expression (*tok*) * Token.t (* "[" *) * expression (*tok*)
  * Token.t (* "]" *)
)

and type_descriptor = (
    type_qualifier (*tok*) list (* zero or more *)
  * type_specifier (*tok*)
  * type_qualifier (*tok*) list (* zero or more *)
  * abstract_declarator (*tok*) option
)

and type_specifier = [
    `Struct_spec of (
        Token.t (* "struct" *)
      * ms_declspec_modifier (*tok*) option
      * anon_choice_type_id_opt_field_decl_list_9aebd83 (*tok*)
    )
  | `Union_spec of (
        Token.t (* "union" *)
      * ms_declspec_modifier (*tok*) option
      * anon_choice_type_id_opt_field_decl_list_9aebd83 (*tok*)
    )
  | `Enum_spec of (
        Token.t (* "enum" *)
      * [
            `Id_opt_enum_list of (
                identifier (*tok*)
              * enumerator_list (*tok*) option
            )
          | `Enum_list of enumerator_list (*tok*)
        ]
    )
  | `Macro_type_spec of (
        identifier (*tok*) * Token.t (* "(" *) * type_descriptor (*tok*)
      * Token.t (* ")" *)
    )
  | `Sized_type_spec of (
        [
            `Signed of Token.t (* "signed" *)
          | `Unsi of Token.t (* "unsigned" *)
          | `Long of Token.t (* "long" *)
          | `Short of Token.t (* "short" *)
        ]
          list (* one or more *)
      * [ `Id of identifier (*tok*) | `Prim_type of primitive_type (*tok*) ]
          option
    )
  | `Prim_type of primitive_type (*tok*)
  | `Id of identifier (*tok*)
]

and update_expression = [
    `Choice_DASHDASH_exp of (
        anon_choice_DASHDASH_d11def2 (*tok*) * expression (*tok*)
    )
  | `Exp_choice_DASHDASH of (
        expression (*tok*) * anon_choice_DASHDASH_d11def2 (*tok*)
    )
]
[@@deriving sexp_of]

type expression_statement = (
    anon_choice_exp_55b4dba (*tok*) option
  * Token.t (* ";" *)
)
[@@deriving sexp_of]

type type_declarator = [
    `Poin_type_decl of (
        ms_based_modifier (*tok*) option
      * Token.t (* "*" *)
      * ms_pointer_modifier (*tok*) list (* zero or more *)
      * type_qualifier (*tok*) list (* zero or more *)
      * type_declarator (*tok*)
    )
  | `Func_type_decl of (type_declarator (*tok*) * parameter_list (*tok*))
  | `Array_type_decl of (
        type_declarator (*tok*)
      * Token.t (* "[" *)
      * type_qualifier (*tok*) list (* zero or more *)
      * anon_choice_exp_508611b (*tok*) option
      * Token.t (* "]" *)
    )
  | `Paren_type_decl of (
        Token.t (* "(" *) * type_declarator (*tok*) * Token.t (* ")" *)
    )
  | `Id of identifier (*tok*)
]
[@@deriving sexp_of]

type anon_choice_decl_f8b0ff3 = [
    `Decl of declarator (*tok*)
  | `Init_decl of (
        declarator (*tok*)
      * Token.t (* "=" *)
      * [
            `Init_list of initializer_list (*tok*)
          | `Exp of expression (*tok*)
        ]
    )
]
[@@deriving sexp_of]

type type_definition = (
    Token.t (* "typedef" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * type_specifier (*tok*)
  * type_declarator (*tok*)
  * (Token.t (* "," *) * type_declarator (*tok*)) list (* zero or more *)
  * Token.t (* ";" *)
)
[@@deriving sexp_of]

type declaration = (
    declaration_specifiers (*tok*)
  * anon_choice_decl_f8b0ff3 (*tok*)
  * (Token.t (* "," *) * anon_choice_decl_f8b0ff3 (*tok*))
      list (* zero or more *)
  * Token.t (* ";" *)
)
[@@deriving sexp_of]

type anon_choice_prep_else_8b52b0f = [
    `Prep_else of (pat_56631e5 * translation_unit (*tok*))
  | `Prep_elif of (
        pat_bfeb4bb
      * preproc_expression (*tok*)
      * Token.t (* "\n" *)
      * translation_unit (*tok*)
      * anon_choice_prep_else_8b52b0f (*tok*) option
    )
]

and compound_statement = (
    Token.t (* "{" *) * translation_unit (*tok*) * Token.t (* "}" *)
)

and declaration_list = (
    Token.t (* "{" *) * translation_unit (*tok*) * Token.t (* "}" *)
)

and function_definition = (
    ms_call_modifier (*tok*) option
  * declaration_specifiers (*tok*)
  * declarator (*tok*)
  * compound_statement (*tok*)
)

and non_case_statement = [
    `Labe_stmt of (
        identifier (*tok*) * Token.t (* ":" *) * statement (*tok*)
    )
  | `Comp_stmt of compound_statement (*tok*)
  | `Exp_stmt of expression_statement (*tok*)
  | `If_stmt of (
        Token.t (* "if" *)
      * parenthesized_expression (*tok*)
      * statement (*tok*)
      * (Token.t (* "else" *) * statement (*tok*)) option
    )
  | `Switch_stmt of (
        Token.t (* "switch" *) * parenthesized_expression (*tok*)
      * compound_statement (*tok*)
    )
  | `Do_stmt of (
        Token.t (* "do" *) * statement (*tok*) * Token.t (* "while" *)
      * parenthesized_expression (*tok*) * Token.t (* ";" *)
    )
  | `While_stmt of (
        Token.t (* "while" *) * parenthesized_expression (*tok*)
      * statement (*tok*)
    )
  | `For_stmt of (
        Token.t (* "for" *)
      * Token.t (* "(" *)
      * [
            `Decl of declaration (*tok*)
          | `Opt_choice_exp_SEMI of expression_statement (*tok*)
        ]
      * expression (*tok*) option
      * Token.t (* ";" *)
      * anon_choice_exp_55b4dba (*tok*) option
      * Token.t (* ")" *)
      * statement (*tok*)
    )
  | `Ret_stmt of (
        Token.t (* "return" *)
      * anon_choice_exp_55b4dba (*tok*) option
      * Token.t (* ";" *)
    )
  | `Brk_stmt of (Token.t (* "break" *) * Token.t (* ";" *))
  | `Cont_stmt of (Token.t (* "continue" *) * Token.t (* ";" *))
  | `Goto_stmt of (
        Token.t (* "goto" *) * identifier (*tok*) * Token.t (* ";" *)
    )
]

and statement = [
    `Case_stmt of (
        [
            `Case_exp of (Token.t (* "case" *) * expression (*tok*))
          | `Defa of Token.t (* "default" *)
        ]
      * Token.t (* ":" *)
      * [
            `Choice_labe_stmt of non_case_statement (*tok*)
          | `Decl of declaration (*tok*)
          | `Type_defi of type_definition (*tok*)
        ]
          list (* zero or more *)
    )
  | `Choice_labe_stmt of non_case_statement (*tok*)
]

and top_level_item = [
    `Func_defi of function_definition (*tok*)
  | `Link_spec of (
        Token.t (* "extern" *)
      * string_literal (*tok*)
      * [
            `Func_defi of function_definition (*tok*)
          | `Decl of declaration (*tok*)
          | `Decl_list of declaration_list (*tok*)
        ]
    )
  | `Decl of declaration (*tok*)
  | `Choice_case_stmt of statement (*tok*)
  | `Type_defi of type_definition (*tok*)
  | `Empty_decl of (type_specifier (*tok*) * Token.t (* ";" *))
  | `Prep_if of (
        pat_3df6e71
      * preproc_expression (*tok*)
      * Token.t (* "\n" *)
      * translation_unit (*tok*)
      * anon_choice_prep_else_8b52b0f (*tok*) option
      * pat_c46d1b2
    )
  | `Prep_ifdef of (
        anon_choice_pat_25b90ba_4a37f8c (*tok*)
      * identifier (*tok*)
      * translation_unit (*tok*)
      * anon_choice_prep_else_8b52b0f (*tok*) option
      * pat_c46d1b2
    )
  | `Prep_incl of (
        pat_ca8830e
      * [
            `Str_lit of string_literal (*tok*)
          | `System_lib_str of system_lib_string (*tok*)
          | `Id of identifier (*tok*)
          | `Prep_call_exp of preproc_call_expression (*tok*)
        ]
      * Token.t (* "\n" *)
    )
  | `Prep_def of preproc_def (*tok*)
  | `Prep_func_def of preproc_function_def (*tok*)
  | `Prep_call of preproc_call (*tok*)
]

and translation_unit = top_level_item (*tok*) list (* zero or more *)
[@@deriving sexp_of]

type ms_unsigned_ptr_modifier (* inlined *) = Token.t (* "__uptr" *)
[@@deriving sexp_of]

type ms_signed_ptr_modifier (* inlined *) = Token.t (* "__sptr" *)
[@@deriving sexp_of]

type null (* inlined *) = Token.t (* "NULL" *)
[@@deriving sexp_of]

type comment (* inlined *) = Token.t
[@@deriving sexp_of]

type continue_statement (* inlined *) = (
    Token.t (* "continue" *) * Token.t (* ";" *)
)
[@@deriving sexp_of]

type break_statement (* inlined *) = (
    Token.t (* "break" *) * Token.t (* ";" *)
)
[@@deriving sexp_of]

type ms_restrict_modifier (* inlined *) = Token.t (* "__restrict" *)
[@@deriving sexp_of]

type field_identifier (* inlined *) = identifier (*tok*)
[@@deriving sexp_of]

type statement_identifier (* inlined *) = identifier (*tok*)
[@@deriving sexp_of]

type type_identifier (* inlined *) = identifier (*tok*)
[@@deriving sexp_of]

type sized_type_specifier (* inlined *) = (
    [
        `Signed of Token.t (* "signed" *)
      | `Unsi of Token.t (* "unsigned" *)
      | `Long of Token.t (* "long" *)
      | `Short of Token.t (* "short" *)
    ]
      list (* one or more *)
  * [ `Id of identifier (*tok*) | `Prim_type of primitive_type (*tok*) ]
      option
)
[@@deriving sexp_of]

type goto_statement (* inlined *) = (
    Token.t (* "goto" *) * identifier (*tok*) * Token.t (* ";" *)
)
[@@deriving sexp_of]

type concatenated_string (* inlined *) = (
    string_literal (*tok*)
  * string_literal (*tok*) list (* one or more *)
)
[@@deriving sexp_of]

type preproc_parenthesized_expression (* inlined *) = (
    Token.t (* "(" *) * preproc_expression (*tok*) * Token.t (* ")" *)
)
[@@deriving sexp_of]

type preproc_unary_expression (* inlined *) = (
    anon_choice_BANG_67174d6 (*tok*) * preproc_expression (*tok*)
)
[@@deriving sexp_of]

type preproc_include (* inlined *) = (
    pat_ca8830e
  * [
        `Str_lit of string_literal (*tok*)
      | `System_lib_str of system_lib_string (*tok*)
      | `Id of identifier (*tok*)
      | `Prep_call_exp of preproc_call_expression (*tok*)
    ]
  * Token.t (* "\n" *)
)
[@@deriving sexp_of]

type abstract_array_declarator (* inlined *) = (
    abstract_declarator (*tok*) option
  * Token.t (* "[" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * anon_choice_exp_508611b (*tok*) option
  * Token.t (* "]" *)
)
[@@deriving sexp_of]

type abstract_function_declarator (* inlined *) = (
    abstract_declarator (*tok*) option
  * parameter_list (*tok*)
)
[@@deriving sexp_of]

type abstract_parenthesized_declarator (* inlined *) = (
    Token.t (* "(" *) * abstract_declarator (*tok*) * Token.t (* ")" *)
)
[@@deriving sexp_of]

type abstract_pointer_declarator (* inlined *) = (
    Token.t (* "*" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * abstract_declarator (*tok*) option
)
[@@deriving sexp_of]

type array_declarator (* inlined *) = (
    declarator (*tok*)
  * Token.t (* "[" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * anon_choice_exp_508611b (*tok*) option
  * Token.t (* "]" *)
)
[@@deriving sexp_of]

type array_field_declarator (* inlined *) = (
    field_declarator (*tok*)
  * Token.t (* "[" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * anon_choice_exp_508611b (*tok*) option
  * Token.t (* "]" *)
)
[@@deriving sexp_of]

type assignment_expression (* inlined *) = (
    assignment_left_expression (*tok*)
  * [
        `EQ of Token.t (* "=" *)
      | `STAREQ of Token.t (* "*=" *)
      | `SLASHEQ of Token.t (* "/=" *)
      | `PERCEQ of Token.t (* "%=" *)
      | `PLUSEQ of Token.t (* "+=" *)
      | `DASHEQ of Token.t (* "-=" *)
      | `LTLTEQ of Token.t (* "<<=" *)
      | `GTGTEQ of Token.t (* ">>=" *)
      | `AMPEQ of Token.t (* "&=" *)
      | `HATEQ of Token.t (* "^=" *)
      | `BAREQ of Token.t (* "|=" *)
    ]
  * expression (*tok*)
)
[@@deriving sexp_of]

type cast_expression (* inlined *) = (
    Token.t (* "(" *) * type_descriptor (*tok*) * Token.t (* ")" *)
  * expression (*tok*)
)
[@@deriving sexp_of]

type comma_expression (* inlined *) = (
    expression (*tok*) * Token.t (* "," *) * anon_choice_exp_55b4dba (*tok*)
)
[@@deriving sexp_of]

type compound_literal_expression (* inlined *) = (
    Token.t (* "(" *) * type_descriptor (*tok*) * Token.t (* ")" *)
  * initializer_list (*tok*)
)
[@@deriving sexp_of]

type conditional_expression (* inlined *) = (
    expression (*tok*) * Token.t (* "?" *) * expression (*tok*)
  * Token.t (* ":" *) * expression (*tok*)
)
[@@deriving sexp_of]

type enum_specifier (* inlined *) = (
    Token.t (* "enum" *)
  * [
        `Id_opt_enum_list of (
            identifier (*tok*)
          * enumerator_list (*tok*) option
        )
      | `Enum_list of enumerator_list (*tok*)
    ]
)
[@@deriving sexp_of]

type field_declaration (* inlined *) = (
    declaration_specifiers (*tok*)
  * (
        field_declarator (*tok*)
      * (Token.t (* "," *) * field_declarator (*tok*))
          list (* zero or more *)
    )
      option
  * bitfield_clause (*tok*) option
  * Token.t (* ";" *)
)
[@@deriving sexp_of]

type function_declarator (* inlined *) = (
    declarator (*tok*)
  * parameter_list (*tok*)
  * attribute_specifier (*tok*) list (* zero or more *)
)
[@@deriving sexp_of]

type function_field_declarator (* inlined *) = (
    field_declarator (*tok*) * parameter_list (*tok*)
)
[@@deriving sexp_of]

type initializer_pair (* inlined *) = (
    [
        `Subs_desi of subscript_designator (*tok*)
      | `Field_desi of field_designator (*tok*)
    ]
      list (* one or more *)
  * Token.t (* "=" *)
  * [ `Exp of expression (*tok*) | `Init_list of initializer_list (*tok*) ]
)
[@@deriving sexp_of]

type macro_type_specifier (* inlined *) = (
    identifier (*tok*) * Token.t (* "(" *) * type_descriptor (*tok*)
  * Token.t (* ")" *)
)
[@@deriving sexp_of]

type parameter_declaration (* inlined *) = (
    declaration_specifiers (*tok*)
  * [
        `Decl of declarator (*tok*)
      | `Abst_decl of abstract_declarator (*tok*)
    ]
      option
)
[@@deriving sexp_of]

type parenthesized_declarator (* inlined *) = (
    Token.t (* "(" *) * declarator (*tok*) * Token.t (* ")" *)
)
[@@deriving sexp_of]

type parenthesized_field_declarator (* inlined *) = (
    Token.t (* "(" *) * field_declarator (*tok*) * Token.t (* ")" *)
)
[@@deriving sexp_of]

type pointer_declarator (* inlined *) = (
    ms_based_modifier (*tok*) option
  * Token.t (* "*" *)
  * ms_pointer_modifier (*tok*) list (* zero or more *)
  * type_qualifier (*tok*) list (* zero or more *)
  * declarator (*tok*)
)
[@@deriving sexp_of]

type pointer_field_declarator (* inlined *) = (
    ms_based_modifier (*tok*) option
  * Token.t (* "*" *)
  * ms_pointer_modifier (*tok*) list (* zero or more *)
  * type_qualifier (*tok*) list (* zero or more *)
  * field_declarator (*tok*)
)
[@@deriving sexp_of]

type preproc_elif_in_field_declaration_list (* inlined *) = (
    pat_bfeb4bb
  * preproc_expression (*tok*)
  * Token.t (* "\n" *)
  * field_declaration_list_item (*tok*) list (* zero or more *)
  * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
)
[@@deriving sexp_of]

type preproc_else_in_field_declaration_list (* inlined *) = (
    pat_56631e5
  * field_declaration_list_item (*tok*) list (* zero or more *)
)
[@@deriving sexp_of]

type preproc_if_in_field_declaration_list (* inlined *) = (
    pat_3df6e71
  * preproc_expression (*tok*)
  * Token.t (* "\n" *)
  * field_declaration_list_item (*tok*) list (* zero or more *)
  * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
  * pat_c46d1b2
)
[@@deriving sexp_of]

type preproc_ifdef_in_field_declaration_list (* inlined *) = (
    anon_choice_pat_25b90ba_4a37f8c (*tok*)
  * identifier (*tok*)
  * field_declaration_list_item (*tok*) list (* zero or more *)
  * anon_choice_prep_else_in_field_decl_list_97ea65e (*tok*) option
  * pat_c46d1b2
)
[@@deriving sexp_of]

type sizeof_expression (* inlined *) = (
    Token.t (* "sizeof" *)
  * [
        `Exp of expression (*tok*)
      | `LPAR_type_desc_RPAR of (
            Token.t (* "(" *) * type_descriptor (*tok*) * Token.t (* ")" *)
        )
    ]
)
[@@deriving sexp_of]

type struct_specifier (* inlined *) = (
    Token.t (* "struct" *)
  * ms_declspec_modifier (*tok*) option
  * anon_choice_type_id_opt_field_decl_list_9aebd83 (*tok*)
)
[@@deriving sexp_of]

type unary_expression (* inlined *) = (
    anon_choice_BANG_67174d6 (*tok*) * expression (*tok*)
)
[@@deriving sexp_of]

type union_specifier (* inlined *) = (
    Token.t (* "union" *)
  * ms_declspec_modifier (*tok*) option
  * anon_choice_type_id_opt_field_decl_list_9aebd83 (*tok*)
)
[@@deriving sexp_of]

type return_statement (* inlined *) = (
    Token.t (* "return" *)
  * anon_choice_exp_55b4dba (*tok*) option
  * Token.t (* ";" *)
)
[@@deriving sexp_of]

type init_declarator (* inlined *) = (
    declarator (*tok*)
  * Token.t (* "=" *)
  * [ `Init_list of initializer_list (*tok*) | `Exp of expression (*tok*) ]
)
[@@deriving sexp_of]

type empty_declaration (* inlined *) = (
    type_specifier (*tok*) * Token.t (* ";" *)
)
[@@deriving sexp_of]

type array_type_declarator (* inlined *) = (
    type_declarator (*tok*)
  * Token.t (* "[" *)
  * type_qualifier (*tok*) list (* zero or more *)
  * anon_choice_exp_508611b (*tok*) option
  * Token.t (* "]" *)
)
[@@deriving sexp_of]

type function_type_declarator (* inlined *) = (
    type_declarator (*tok*) * parameter_list (*tok*)
)
[@@deriving sexp_of]

type parenthesized_type_declarator (* inlined *) = (
    Token.t (* "(" *) * type_declarator (*tok*) * Token.t (* ")" *)
)
[@@deriving sexp_of]

type pointer_type_declarator (* inlined *) = (
    ms_based_modifier (*tok*) option
  * Token.t (* "*" *)
  * ms_pointer_modifier (*tok*) list (* zero or more *)
  * type_qualifier (*tok*) list (* zero or more *)
  * type_declarator (*tok*)
)
[@@deriving sexp_of]

type case_statement (* inlined *) = (
    [
        `Case_exp of (Token.t (* "case" *) * expression (*tok*))
      | `Defa of Token.t (* "default" *)
    ]
  * Token.t (* ":" *)
  * [
        `Choice_labe_stmt of non_case_statement (*tok*)
      | `Decl of declaration (*tok*)
      | `Type_defi of type_definition (*tok*)
    ]
      list (* zero or more *)
)
[@@deriving sexp_of]

type do_statement (* inlined *) = (
    Token.t (* "do" *) * statement (*tok*) * Token.t (* "while" *)
  * parenthesized_expression (*tok*) * Token.t (* ";" *)
)
[@@deriving sexp_of]

type for_statement (* inlined *) = (
    Token.t (* "for" *)
  * Token.t (* "(" *)
  * [
        `Decl of declaration (*tok*)
      | `Opt_choice_exp_SEMI of expression_statement (*tok*)
    ]
  * expression (*tok*) option
  * Token.t (* ";" *)
  * anon_choice_exp_55b4dba (*tok*) option
  * Token.t (* ")" *)
  * statement (*tok*)
)
[@@deriving sexp_of]

type if_statement (* inlined *) = (
    Token.t (* "if" *)
  * parenthesized_expression (*tok*)
  * statement (*tok*)
  * (Token.t (* "else" *) * statement (*tok*)) option
)
[@@deriving sexp_of]

type labeled_statement (* inlined *) = (
    identifier (*tok*) * Token.t (* ":" *) * statement (*tok*)
)
[@@deriving sexp_of]

type linkage_specification (* inlined *) = (
    Token.t (* "extern" *)
  * string_literal (*tok*)
  * [
        `Func_defi of function_definition (*tok*)
      | `Decl of declaration (*tok*)
      | `Decl_list of declaration_list (*tok*)
    ]
)
[@@deriving sexp_of]

type preproc_elif (* inlined *) = (
    pat_bfeb4bb
  * preproc_expression (*tok*)
  * Token.t (* "\n" *)
  * translation_unit (*tok*)
  * anon_choice_prep_else_8b52b0f (*tok*) option
)
[@@deriving sexp_of]

type preproc_else (* inlined *) = (pat_56631e5 * translation_unit (*tok*))
[@@deriving sexp_of]

type preproc_if (* inlined *) = (
    pat_3df6e71
  * preproc_expression (*tok*)
  * Token.t (* "\n" *)
  * translation_unit (*tok*)
  * anon_choice_prep_else_8b52b0f (*tok*) option
  * pat_c46d1b2
)
[@@deriving sexp_of]

type preproc_ifdef (* inlined *) = (
    anon_choice_pat_25b90ba_4a37f8c (*tok*)
  * identifier (*tok*)
  * translation_unit (*tok*)
  * anon_choice_prep_else_8b52b0f (*tok*) option
  * pat_c46d1b2
)
[@@deriving sexp_of]

type switch_statement (* inlined *) = (
    Token.t (* "switch" *) * parenthesized_expression (*tok*)
  * compound_statement (*tok*)
)
[@@deriving sexp_of]

type while_statement (* inlined *) = (
    Token.t (* "while" *) * parenthesized_expression (*tok*)
  * statement (*tok*)
)
[@@deriving sexp_of]

let dump_tree root =
  sexp_of_translation_unit root
  |> Print_sexp.to_stdout
